### PR TITLE
Standardize Quarkus build and version

### PR DESCRIPTION
**Pull request by mabulgu**
Quarkus versions of the applications are updated and standardized to `1.12.1.Final`.

Related to issue: https://github.com/RedHatTraining/DO400/issues/588

### CODE REVIEW

**Review by enolredhat — COMMENTED** [review]
It looks ok!

I think the apps in `calculator-microservices` are still using the `1.12.0.Final` version, should we also change them?

**Comment by mabulgu** [comment]
> It looks good!
> 
> I think the apps in `calculator-microservices` are still using the `1.12.0.Final` version, should we also change them?

Whopp. I must have missed it. Let me check.

**Comment by mabulgu** [comment]
Done, thanks @enolredhat !

**Review by enolredhat — APPROVED** [review]

**Review by jramcast — CHANGES_REQUESTED** [review]
We need to make sure me merge this into the `main` branch

**Comment by mabulgu** [comment]
@jramcast I opened the PR for the main branch merge: https://github.com/RedHatTraining/DO400-apps/pull/39

**Pull request merged**
