### PR TITLE
Revert "Changes regarding OCP 4.6"

### PR DESCRIPTION
**Pull request by mabulgu**
Reverts RedHatTraining/DO400-apps#2

If this needs to be reverted since EA is now using the master (which I forgot and merged by thinking EA as the stage which is of course not!) we can use this PR. Otherwise, I will delete the PR.

@jramcast, @richardallred  FYI

### CODE REVIEW

**Review by jramcast — APPROVED** [review]
Nicely seen!

Yeah, let's revert this and open another PR, with the OCP 4.6 changes ready to be merged after OCP 4.6 is available in EA.

**Comment by mabulgu** [comment]
Sure thanks!

**Comment by mabulgu** [comment]
Created the PR again from scratch. Thanks

https://github.com/RedHatTraining/DO400-apps/pull/30

**Comment by richardallred** [comment]
Just for clarity, stuff in `earlyaccess` doesn't automatically go out to prod, it has to be pushed.

**Comment by mabulgu** [comment]
Yeah. So for the PRs like this we have to either push it into a `develop` branch after review or make this PR stay until the EA release because a `DO400-apps: version+1 but DO400: version` situation comes out. That was the part that confused me in the first place.

**Comment by richardallred** [comment]
Ohhh, this is the DO400-apps repo.  Sorry I didn't realize that.

**Pull request merged**
